### ISSUE TITLE
Not working on jenkins 1.511?

### ISSUE THREAD

**Issue by uorbe001** [codevise/jenkins-nvm-plugin#1]
I built the plugin using jpi and updated it manually to my jenkins (v1.511) and it doesn't seem to do anything. I checked the plugin is on the plugins folder and restarted jenkins just in case, but I can still find no option on the project config nor the global config for nvm. 

What are the supported versions?

**Comment by tf** [comment]
We are using the plugin with v1.500 at the moment. Did jenkins unpack the uploaded jpi file in the plugin folder?

**Comment by uorbe001** [comment]
@tf I do think so, on my plugins folder I have the nvm.jpi file and a nvm folrder with META-INF and WEB-INF. I built the plugin by running `jpi build` and uploaded  `pkg/nvm.hpi` through the web interface. Is it possible I missed something?

**Comment by tf** [comment]
That is also exactly what I see in the plugins directory of our jenkins installation. Since this plugin is written in ruby, have you made sure the correct version of JRuby is available on your system? Maybe take a look at the [Getting Started page](https://github.com/jenkinsci/jenkins.rb/wiki/Getting-Started-With-Ruby-Plugins) of the jenkins.rb project.

Otherwise did you find anything interesting in the jenkins logs?

**Comment by uorbe001** [comment]
Okay, I found the problem. There was a message on the logs saying there is an unmet dependency 'ruby-runtime' installing the 'ruby runtime' plugin makes nvm work. I guess it should have been obvious that it needs that after reading what that plugin does :P.

Thanks for the help and for the great plugin :)

**Comment by tf** [comment]
That's great to hear. I've added a note to README mentioning the ruby-runtime dependency. Would have been nice, if Jenkins resolved or at least warned about missing dependencies during installation.
